### ISSUE TITLE
unable to launch terminal or iterm2 after running script

### ISSUE THREAD

**Issue by mike-u** [tylucaskelley/osx#11]
I had a prior setup for a few months with dotfiles and such. Running the script made me unable to launch the terminal or iterm2 until I changed the default shell to /bin/bash from /usr/local/bin/bash, which must have been set by the script. I don't particularly know what this means, but let me know if you need any more information.

**Comment by tylucaskelley** [comment]
nope that's enough for me to go off of! didn't really consider iTerm since I don't use it myself, thanks for opening the issue

**Comment by tylucaskelley** [comment]
hmm, haven't been able to duplicate the issue myself. can you share what your setup looked like prior to running my script?

**Comment by mike-u** [comment]
If I can i will. How would I do that?

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Thu, Jan 14, 2016 at 8:17 AM -0800, "Ty-Lucas Kelley" <notifications@github.com<mailto:notifications@github.com>> wrote:


hmm, haven't been able to duplicate the issue myself. can you share what your setup looked like prior to running my script?

-

**Comment by tylucaskelley** [comment]
Hmm, do you have any dotfiles that you can share (i.e. bash_profile, vimrc, etc) that existed before running the script?

**Comment by mike-u** [comment]
Yes, but AFAIK they were all overwritten by the script :/ they wouldn't be backed up somewhere if I hadn't been already, right? Since then I've been backing them up but idk about beforehand.


~ Mike Urich
    University of Pittsburgh


________________________________

**Comment by tylucaskelley** [comment]
ah wasn't sure if you kept a backup. no worries. not sure what i can do without more info though, so i'll have to close this one. i'll make a note in the readme to warn people about running if they have an existing setup

**Comment by mike-u** [comment]
Sorry to reopen this, but my iTerm2 often opens saying:
mike at fq-130-49-xx-xxx
where xx-xxx are some other numbers, but I can't tell if this is some personal information so I've omitted them. 

It will sometimes open like:
mike at Mikes-MacBook-Pro in ~
which is how it used to all the time. Can you think of anything that might be causing this issue?

**Comment by mike-u** [comment]
It also always says this before anything:
bash: shopt: globstar: invalid shell option name

**Comment by tylucaskelley** [comment]
@mike-u it's your hostname, so it can change depending on what network you're connected to. mine changes whenever i'm on the school networ

**Comment by tylucaskelley** [comment]
if the globstar option isn't working, disable it by removing the "globstar" line from the `options` array in `~/.bashrc`

**Comment by mike-u** [comment]
Cool, thanks!
