### ISSUE TITLE
Sudo Permissions

### ISSUE THREAD

**Issue by merqurio** [tylucaskelley/osx#18]
Please correct me if I'm wrong but you give the whole script sudo capabilities, meaning that later on you have to use root permission to modify almost any file created by the script, am I wrong ?

Thanks in advance ! :v:

**Comment by tylucaskelley** [comment]
Nope, no worries there! Should be owned by the user you were logged in as. Run `ls -al` to confirm.

**Comment by merqurio** [comment]
great ! thanks!
